# Generated by Django 3.0.6 on 2020-05-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200507_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
